name: Update data and deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]' || github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest datasets
        run: python scripts/fetch_data.py

      - name: Commit updated data
        run: |
          if [[ -n "$(git status --short data)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data
            git commit -m "chore: daily data refresh"
            git push
          else
            echo "No data changes to commit."
          fi

      - name: Prepare Pages bundle
        run: |
          rm -rf public
          mkdir -p public
          rsync -a \
            --include='index.html' \
            --include='css/***' \
            --include='js/***' \
            --include='data/***' \
            --include='LICENSE' \
            --exclude='*' \
            ./ public/

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: needs.build.result == 'success'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
